//Strings: Properties, Methods & Template Literals

//Let's start with String Concatination_
const str = 'Hello';
const str2 = 'World';
//let's concat them with regular method and also add a space...
let addSting = (str + ' ' + str2);
console.log(addSting);
//There's another method using a function where you can add a external string...
let newStr = (addSting.concat('! JavaScript is awesome.'))
console.log(newStr);

//There's a new thing called Template Literals...
let someStr = 'My name is';
let anotherStr = 'I am doing some'
console.log(`Hi! ${someStr} Cyborg, 
            ${anotherStr} Js.`)

//Let's look into some common string methods...
//How do you get the length of a String ?
console.log(newStr.length);
//if you trying to get a simple charactor out of string...
console.log(newStr[0], newStr[4]);
//also there's this one...
console.log(newStr.charAt(3));
//if you are looking for the index of a character...
console.log(newStr.indexOf('W'));
//The output will be -1 if the char isn't present in the string...
console.log(newStr.indexOf('z'));
//What if you want to get a entire word ? It throws to you the index of the first word in it...
console.log(newStr.indexOf('World'));
//If there's multiple appearence's of the same char, then we can use this method...
console.log(newStr.lastIndexOf('o'));
//Also we can check whether the string with the word or char you know or not...
console.log(newStr.endsWith('awesome.'));
console.log(newStr.endsWith('World'));
//if we are checking whether something is in the str or not...
console.log(newStr.includes('Never'));
console.log(newStr.includes('World'));
//What if you want a substring from the present string ?
console.log(newStr.substring(0,5));
//there's another method to slice a string or array...
console.log(newStr.slice(6,11));
//This is how you split a string into an array...
console.log(newStr.split(' '));
//How about we wanna replace something in the array...
console.log(newStr.replace('awesome','fantastic'));
